[package]
name = "tutorial12-camera"
version = "0.1.0"
authors = ["Ben Hansen <https://github.com/sotrh>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
glam.workspace = true
image.workspace = true
tobj.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
web-time.workspace = true
winit.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster.workspace = true
wgpu.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
reqwest.workspace = true
tracing-wasm.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
wgpu = { workspace = true, features = ["webgl"] }

[build-dependencies]
anyhow.workspace = true
fs_extra.workspace = true
